batch_size: 30 # train_type noise
beta_end: 0.005
beta_start: 0.0001
epochs: 20
timesteps: 1000
model_name: ~
ddpm_arch: unet_cond
ddpm_params:
    in_channels: 1
    out_channels: 1
    down_channels: [128, 128, 128, 128, 128]    
    up_channels: [128, 128, 128, 128, 128]
    time_emb_dim: 64   
# ddpm_arch: fno2d 
# ddpm_params:
#     in_channels: 1
#     out_channels: 1
lr: .001
train_type: noise
data_type: delta_mean
loss_function_start_batch: -1 # -1 means always use loss_function_start loss
loss_function_start: mse_loss
loss_args_start: {}
loss_function: spectral_sqr_abs2
loss_args_end: 
    lambda_fft: 0.2
    lat_lon_bal: .5
beta_scheduler: linear
reconstuct_condition: true

# batch_size: 100 # train_type noise
# beta_end: 0.02
# beta_start: 0.0001
# epochs: 20
# timesteps: 1000
# model_name: ~
# ddpm_arch: fno2d
# ddpm_params:
#     modes1: 64
#     modes2: 64
#     width: 20
#     padding: 
#     channels: 3
#     channelsout: 3
#     gridx: [0, 1]
#     gridy: [0, 1]
#     padval: 0
#     pbias: true
#     fourier_layers: 4
# lr: .01
# train_type: noise
# loss_function_start: mse_loss
# loss_args_start: {}
# loss_function_start_batch: 200
# loss_function: spectral_sqr_abs2
# loss_args_end: 
#     lambda_fft: 0.2
#     lat_lon_bal: .5
# beta_scheduler: linear